#!/bin/bash

coffee << EOF
loadfits "LUVOIRpup4096.fits.gz" pup

creaim im0b 8192 8192
addim im0b pup pupb 2051 2051
imcontract pupb pupc 2 2
pupcn=pupc/4
listim
savefits pupcn "!pupLUVOIRap6.4096.948.fits"
rm im0b
rm pupb
rm pupc
rm pupcn


creaim im0b 8192 8192
addim im0b pup pupb 2051 2051
imcontract pupb pupc 4 4
pupcn=pupc/16
listim
savefits pupcn "!pupLUVOIRap6.2048.474.fits"
rm im0b
rm pupb
rm pupc
rm pupcn

imcontract pup pupc 5 5
pupcn=pupc/25
listim
creaim im0 2048 2048
addim im0 pupcn pupcn1 615 615
savefits pupcn1 "!pupLUVOIRap6.2048.370.fits"
rm pupc
rm pupcn
rm im0
rm pupcn1

imcontract pup pupc 9 9
pupcn=pupc/81
listim
creaim im0 1024 1024
addim im0 pupcn pupcn1 285 285
savefits pupcn1 "!pupLUVOIRap6.1024.208.fits"

exitCLI
EOF

rm pupLUVOIRap6.4096.948.fits.gz
gzip pupLUVOIRap6.4096.948.fits

rm pupLUVOIRap6.2048.474.fits.gz
gzip pupLUVOIRap6.2048.474.fits

rm pupLUVOIRap6.2048.370.fits.gz
gzip pupLUVOIRap6.2048.370.fits

rm pupLUVOIRap6.1024.208.fits.gz
gzip pupLUVOIRap6.1024.208.fits

