#!/bin/bash


# number of arguments to script
NBARGS=0


echo "Set PIAACMC configuration for SPEED PIAACMC"


# ===========================================
#    SET PARAMETER VALUES FOR PIAACMC
# ===========================================

mkdir -p conf

# PIAA optics (PIAACMC)
echo "1" > ./conf/conf_PIAAmode.txt             # PIAA mode (0: classical apodization, 1: PIAA)
echo "1" > conf/conf_invPIAAmode.txt            # inverse PIAA 
echo "1.0" > ./conf/conf_fpmradld.txt           # focal plane mask radius [l/D]
echo "0.3" > conf/conf_coin.txt                 # input central obstruction
echo "0.25" > conf/conf_coout.txt               # output central obstruction
echo "0" > conf/conf_PIAAcirc.txt               # 1 if forcing PIAA shapes to be circular

echo "0.5" > conf/conf_REGPIAACALPHA.txt
echo "1000.0" > conf/conf_REGPIAACCOEFF.txt  
echo "0.5" > conf/conf_REGPIAAFALPHA.txt  
echo "1000.0" > conf/conf_REGPIAAFCOEFF.txt


# LYOT STOP(S) DESIGN: 
echo "0.80" > ./conf/conf_LStransm.txt          # Lyot stop transmission
echo "1650" > ./conf/conf_lambda.txt            # Wavelength for monochromatic design [nm]

 
# FOCAL PLANE MASK DESIGN: 
echo "Mirror" > ./conf/conf_fpmmaterial.txt     # focal plane mask material
echo "2" > ./conf/conf_FPMsectors.txt           # mask geometry: 0=disk, 1=sectors, 2=hexagonal tiling
echo "20" > ./conf/conf_NBrings.txt             # number of rings in focal plane mask
echo "2.00" > ./conf/conf_maskradld.txt         # mask outer radius at central wavelength [l/D]
echo "-4.25e-7" > ./conf/conf_fpmminsag.txt      # min focal plane mask sag
echo "4.25e-7" > ./conf/conf_fpmmaxsag.txt       # max focal plane mask sag
echo "0.001" > ./conf/conf_fpmregsag_coeff.txt    # sag regularization coefficient
echo "1.0" > ./conf/conf_fpmregsag_alpha.txt    # sag regularization coefficient exponent
echo "0" > ./conf/conf_fpmccnbr.txt             # how many central rings replaced by cone (set to 0 if no central cone)
echo "0" > ./conf/conf_fpmccz.txt               # sag at cone center (sag at cone edge will be midpoint between minsag and maxsag)
echo "0" > ./conf/conf_fpmocradld.txt           # outer cone outer radius [l/D]
echo "0" > ./conf/conf_fpmocz.txt               # sag at inner edge of outer cone (sag = 0 at outer edge), set to 0 if no outer cone


# OPTIMIZATION PARAMETERS: 
echo "1650" > ./conf/conf_mlambda.txt           # central wavelength for polychromatic design [nm]
echo "1.0" > ./conf/conf_mlambdaB.txt           # spectral bandwidth [%]
echo "5" > ./conf/conf_nblambda.txt             # Number of wavelength values
echo "30" > ./conf/conf_ssize.txt               # source angular size for mask optimization (20: 0.01 l/D; 10: 0.1 l/D)
echo "1" > ./conf/conf_extmode.txt              # source extent mode (0: 1 point, 1: 3 points; 2: 6 points)


# OPTICAL DESIGN: 
echo "1024" > ./conf/conf_size.txt              # array size
echo "0.00385" > ./conf/conf_beamrad.txt        # beam radius [mm]
echo "0.0000171112" > ./conf/conf_pscale.txt    # pixel scale in pupil [m/pix]
echo "78" > ./conf/conf_Fratio.txt              # F ratio at focal plane mask
echo "0.0" > ./conf/conf_prePIAA0maskpos.txt    # pre-PIAA optic 0 mask distance from pupil plane [m] (if prePIAA0mask.fits exists)
echo "1.0" > ./conf/conf_pupoutmaskrad.txt      # output pupil mask radius (scaled to pupil radius)

# PIAA shapes
echo "0.15" > ./conf/conf_PIAAsep.txt             # distance between PIAA elements
echo "0.00" > ./conf/conf_PIAA0pos.txt            # distance between PIAA elements
echo "1.15" > ./conf/conf_PIAAr0lim.txt           # PIAA element 0 oversizing
echo "1.50" > ./conf/conf_PIAAr1lim.txt           # PIAA element 1 oversizing
echo "40" > ./conf/conf_piaaNBCmodesmax.txt       # maximum number of radial cosine modes for PIAA optics
echo "10.0" > ./conf/conf_piaaCPAmax.txt           # maximum spatial frequency (CPA) for PIAA optics


# LYOT STOP(s)
echo "1" > ./conf/conf_NBls.txt                   # Number of Lyot stops
echo "-0.25" > ./conf/conf_LyotZmin.txt           # conjugation range for Lyot stop (min)
echo "-0.05" > ./conf/conf_LyotZmax.txt             # conjugation range for Lyot stop (max)





# ===========================================
#    SET PUPIL
# ===========================================

rm pup_1024.fits &> /dev/null
cp examples/pupSPEED_1024_225.fits.gz .
gunzip pupSPEED_1024_225.fits.gz
cp pupSPEED_1024_225.fits pup_1024.fits




exit 

# =============== NOTES ==================================

# After step 3
# Average contrast = 3.77276e-05

# step 4 takes 55mn
# BEST SOLUTION: 13.256721149582 / 12.274741805168    0.000001060413 / 0.000023672850  -> 0.700170293288  0.015223838145

# step 5
# best solution: 
# +0.34777401  5.49534e-07         5     0.000729     0.000243

# step 6
# BEST SOLUTION: 67.236710310916 / 74.707455901018    0.000000180322 / 0.000024925039  -> 0.600521312855  0.002950946329

# step 7 takes 33mn
# Average contrast = 2.37425e-07

# step 8 takes 43mn
# Average contrast = 2.00018e-07

# step 9
# BEST SOLUTION: 25.200020604773 / 27.391326744318    0.000000515976 / 0.000023885246  -> 0.650169651832  0.004193351711

# step 10
# Average contrast = 6.43535e-06

# step 11
# Average contrast = 2.50336e-07

# step 12 ? takes 6h35mn
# Average contrast = 2.26e-07

# step 13
# BEST SOLUTION: 14.102314473938 / 15.002462206317    0.000001047947 / 0.000023394554  -> 0.700011480409  0.009688432326

# step 14
# Average contrast = 7.80178e-06

# step 15 takes 36 mn
# Average contrast = 2.7011e-07

# step 16 takes 103mn
# Average contrast = 2.45855e-07


# step 17 takes ?
# Average contrast = 1.75886e-07


